apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  labels:
    role: nfs-server
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-server
  nfs:
    path: "/"
    server: 172.30.5.243
  persistentVolumeReclaimPolicy: Delete
