apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-app-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  volumeName: nfs
status: {}
